[deps]
AbstractMCMC = "80f14c24-f653-4e6a-9b94-39d6b0f70001"
Accessors = "7d9f7c33-5ae7-4f3b-8dc6-eff91059b697"
DSP = "717857b8-e6f2-59f4-9121-6e50c889abd2"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
MCMCChains = "c7f686f2-ff18-58e9-bc7b-31028e88f75d"
MCMCTesting = "9963b6a1-5d46-439c-8efc-3a487843c7fa"
MKL = "33e6dc65-8f57-5167-99aa-e5a354878fb2"
Plotly = "58dd65bb-95f3-509e-9936-c39a10fdeae7"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
ReversibleJump = "99282aa0-03f8-4e20-afcb-eb89a1952536"
SignalAnalysis = "df1fea92-c066-49dd-8b36-eace3378ea47"
SimpleUnPack = "ce78b400-467f-4804-87d8-8f486da07d0a"
SinusoidDetection = "3653250f-bd0d-40d6-b491-ffd0041c82e6"
StatsPlots = "f3b207a7-027a-5e70-b257-86293d7955fd"
WAV = "8149f6b0-98f6-5db9-b78f-408fbbb8ef88"
